# Automate Pull Request Reviews
#
# References:
#
# - https://github.com/flex-development/flautoreview

---
name: Flautoreview
on:
  pull_request:
    types: [review_requested]
jobs:
  flautoreview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Automate reviews
        uses: ./
        with:
          body: lgtm ğŸ‘ğŸ¾
          reviewers: flexdevelopment
          senders: unicornware
          token: ${{ secrets.PAT_REPO_ADMIN }}
